version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - bodyclose
    - noctx
    - exhaustive
    - nilerr
    - wastedassign
    - whitespace
    - tparallel
    - errorlint
    - durationcheck
    - errname
    - makezero

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  exhaustive:
    default-signifies-exhaustive: true

  errorlint:
    errorf: true
    asserts: true
    comparison: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/danpasecinic/needle

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam

    - path: examples/
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10
